image:
  - Visual Studio 2019
  - Ubuntu2004

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  clone_folder: c:\projects\source
  build_script:
  - cmd: >-
      mkdir build

      cd build

      cmake c:\projects\source -G "Visual Studio 16 2019" -A x64 -DBUILD_SHARED_LIBS=1

      cmake --build . --config "Release"

-
  matrix:
    only:
      - image: Ubuntu2004
  clone_folder: /home/appveyor/projects/source
  build_script:
    - sudo apt install build-essential make cmake ninja-build clang libhidapi-dev libevdev-dev libgtk-3-dev libappindicator3-dev -y
    - mkdir build
    - cd build
    - cmake /home/appveyor/projects/source -G "Ninja" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
    - cmake --build .

