image:
  - Visual Studio 2019
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake c:\projects\source -G "Visual Studio 16 2019" -A x64 -DBUILD_SHARED_LIBS=1

    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Debug

